// theme.js — the full token system for kata-kata.
// Yellow + white in light mode; warm near-black + amber in dark mode.
// Everything visual derives from here so the two modes stay in lockstep.

export function getTheme(dark) {
  const c = dark
    ? {
        bg: "#16140f",
        surface: "#211d16",
        surfaceAlt: "#1f1b12",
        inputBg: "#16140f",
        ink: "#f7f3e8",
        body: "#d8d2c4",
        muted: "#8f897a",
        accent: "#f4c430",
        accentInk: "#f4c430",
        line: "#332e24",
        danger: "#e88a82",
        tagBg: "#2c2718",
        tagInk: "#f4c430",
      }
    : {
        bg: "#fdfaf0",
        surface: "#ffffff",
        surfaceAlt: "#fffdf5",
        inputBg: "#fdfaf0",
        ink: "#1a1810",
        body: "#3d392e",
        muted: "#8a8472",
        accent: "#f4c430",
        accentInk: "#1a1810",
        line: "#ece5d0",
        danger: "#c0392b",
        tagBg: "#fbf2cf",
        tagInk: "#8a6d00",
      };

  return {
    raw: c,
    dark,

    page: { background: c.bg, color: c.body, transition: "background .4s, color .4s" },
    ink: c.ink,
    body: c.body,
    muted: c.muted,
    accent: c.accent,
    accentInk: c.accentInk,
    danger: c.danger,
    line: c.line,

    nav: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "20px 28px",
      borderBottom: `1px solid ${c.line}`,
      background: c.bg,
      position: "sticky",
      top: 0,
      zIndex: 10,
    },

    card: {
      background: c.surface,
      border: `1px solid ${c.line}`,
      borderRadius: 16,
      padding: 28,
      boxShadow: dark ? "none" : "0 1px 2px rgba(60,50,20,.04)",
    },

    primaryBtn: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      background: c.accent,
      color: "#1a1810",
      border: "none",
      borderRadius: 12,
      padding: "12px 20px",
      fontSize: 14,
      fontWeight: 700,
      fontFamily: "inherit",
      cursor: "pointer",
      letterSpacing: "-0.01em",
    },

    iconBtn: {
      display: "grid",
      placeItems: "center",
      width: 44,
      height: 44,
      borderRadius: 12,
      background: c.surface,
      border: `1px solid ${c.line}`,
      color: c.ink,
      cursor: "pointer",
    },

    ghostIcon: {
      display: "grid",
      placeItems: "center",
      width: 34,
      height: 34,
      borderRadius: 9,
      background: "transparent",
      border: "none",
      color: c.muted,
      cursor: "pointer",
    },

    segmented: {
      display: "flex",
      background: c.surface,
      border: `1px solid ${c.line}`,
      borderRadius: 12,
      padding: 4,
      gap: 4,
    },
    segBtn: {
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      border: "none",
      background: "transparent",
      color: c.muted,
      padding: "8px 14px",
      borderRadius: 9,
      fontSize: 13,
      fontWeight: 500,
      fontFamily: "inherit",
      cursor: "pointer",
    },
    segBtnActive: { background: c.accent, color: "#1a1810", fontWeight: 700 },

    select: {
      background: c.surface,
      color: c.ink,
      border: `1px solid ${c.line}`,
      borderRadius: 12,
      padding: "11px 14px",
      fontSize: 13,
      fontFamily: "inherit",
      cursor: "pointer",
    },

    tag: {
      display: "inline-block",
      background: c.tagBg,
      color: c.tagInk,
      borderRadius: 999,
      padding: "3px 12px",
      fontSize: 11,
      fontWeight: 700,
      letterSpacing: "0.03em",
      textTransform: "uppercase",
    },

    sentence: {
      fontSize: 14,
      lineHeight: 1.6,
      color: c.body,
      paddingLeft: 14,
      borderLeft: `2px solid ${c.accent}`,
    },

    aiBtn: {
      display: "inline-flex",
      alignItems: "center",
      gap: 7,
      background: "transparent",
      color: c.accentInk,
      border: `1px dashed ${c.accent}`,
      borderRadius: 10,
      padding: "8px 14px",
      fontSize: 13,
      fontWeight: 600,
      fontFamily: "inherit",
      cursor: "pointer",
    },

    face: {
      position: "absolute",
      inset: 0,
      backfaceVisibility: "hidden",
      WebkitBackfaceVisibility: "hidden",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: 36,
      borderRadius: 20,
      border: `1px solid ${c.line}`,
    },
    faceFront: { background: c.surface },
    faceBack: { background: c.surfaceAlt, transform: "rotateY(180deg)" },

    navBtn: {
      display: "grid",
      placeItems: "center",
      width: 44,
      height: 44,
      borderRadius: 12,
      background: c.surface,
      border: `1px solid ${c.line}`,
      color: c.ink,
      cursor: "pointer",
    },

    markBtn: {
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      border: "none",
      borderRadius: 12,
      padding: "11px 16px",
      fontSize: 13,
      fontWeight: 700,
      fontFamily: "inherit",
      cursor: "pointer",
    },
    markKnown: { background: c.accent, color: "#1a1810" },
    markUnknown: { background: c.surface, color: c.muted, border: `1px solid ${c.line}` },

    overlay: {
      position: "fixed",
      inset: 0,
      background: "rgba(20,16,8,.5)",
      backdropFilter: "blur(3px)",
      display: "grid",
      placeItems: "center",
      padding: 20,
      zIndex: 50,
    },
    modal: {
      background: c.surface,
      border: `1px solid ${c.line}`,
      borderRadius: 18,
      padding: 32,
      width: "100%",
      maxWidth: 460,
      boxShadow: "0 20px 60px rgba(20,16,8,.25)",
    },
    label: {
      display: "block",
      fontSize: 12,
      fontWeight: 600,
      color: c.muted,
      margin: "16px 0 7px",
      letterSpacing: "0.02em",
    },
    input: {
      width: "100%",
      boxSizing: "border-box",
      background: c.inputBg,
      color: c.ink,
      border: `1px solid ${c.line}`,
      borderRadius: 11,
      padding: "12px 14px",
      fontSize: 14,
      fontFamily: "inherit",
      outline: "none",
    },

    chip: {
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      background: "transparent",
      color: c.muted,
      border: `1px solid ${c.line}`,
      borderRadius: 999,
      padding: "6px 13px",
      fontSize: 12,
      fontWeight: 600,
      fontFamily: "inherit",
      cursor: "pointer",
    },
    chipActive: {
      background: c.accent,
      color: "#1a1810",
      borderColor: c.accent,
    },
  };
}
